### ISSUE TITLE
Add GPTs page to janus-idp.io

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/janus-idp.github.io#152]
## Goal

 The Goal of this epic is to provide a Golden Path Templates (GPTs) page to [the Janus community site](https://janus-idp.io/) to provide discovery of the details of the Sample GPTs which we have available.

## Enhancement

We can take inspiration from the [Plugins page[(https://janus-idp.io/plugins/) with the following changes:
#### Header
- `Sample GPTs`
- `Have a GPT idea?`
- Button -> `Submit a proposal for a GPT!` 

The CTA should reference a new Issue template for [this repo](https://github.com/janus-idp/software-templates/issues) similar to this [plugin issue template](https://github.com/janus-idp/backstage-plugins/issues/new?assignees=&labels=plugin&projects=&template=plugin.yaml&title=%F0%9F%94%8C+Plugin%3A+)

#### Search
Include a search field, but do not provide the filter dropdown as the Plugins page has

#### GPT Cards
Each card should contain
- Title 
- Description

#### Header
- Title
- Description
- `GitHub` link, rather than `NPM` (linking to the GH URL of the Software Template, ex https://github.com/janus-idp/software-templates/tree/main/scaffolder-templates/ansible-job)
- Pull in the README (ex https://github.com/janus-idp/software-templates/blob/main/scaffolder-templates/ansible-job/README.md)

## Notes
GPTsList should include:
- Title
- Description
- href
- githubUrl

As a starter, include the following in the GPTs page:
- https://github.com/janus-idp/software-templates/tree/main/scaffolder-templates/ansible-job
- https://github.com/janus-idp/software-templates/tree/main/scaffolder-templates/quarkus-web-template
- https://github.com/janus-idp/software-templates/tree/main/scaffolder-templates/documentation-template

Be sure to add README.md to the above scaffolder-templates directories if they don't exist

## Issues in Epic
- [x] - https://github.com/janus-idp/software-templates/issues/136
- [x] - https://github.com/janus-idp/software-templates/issues/137
- [ ] - https://github.com/janus-idp/software-templates/issues/140
- [x] - https://github.com/janus-idp/janus-idp.github.io/issues/153
- [x] - https://github.com/janus-idp/janus-idp.github.io/issues/154

**Comment by Zaperex** [comment]
UPDATE: The Golden Path Templates to add to the homepage should be updated to be the following:

- https://github.com/janus-idp/software-templates/blob/main/scaffolder-templates/go-backend-template/template.yaml
- https://github.com/janus-idp/software-templates/blob/main/scaffolder-templates/nodejs-backend-template/template.yaml
- https://github.com/janus-idp/software-templates/blob/main/scaffolder-templates/python-backend-template/template.yaml
- https://github.com/janus-idp/software-templates/blob/main/scaffolder-templates/dotnet-frontend-template/template.yaml
- https://github.com/janus-idp/software-templates/blob/main/scaffolder-templates/spring-boot-backend-template/template.yaml
- https://github.com/janus-idp/software-templates/blob/main/scaffolder-templates/quarkus-backend-template/template.yaml
- https://github.com/janus-idp/software-templates/blob/main/scaffolder-templates/argocd-template/template.yaml
- https://github.com/janus-idp/software-templates/blob/main/scaffolder-templates/ansible-job/template.yaml

**Comment by kadel** [comment]
this is already done
